#! /bin/sh
#
#  docker init

set -e

# setting up timezone
cp /usr/share/zoneinfo/${TZ} /etc/localtime
echo "${TZ}" > /etc/timezone

# user and priv
mkdir -p \
    /config/.config/qBittorrent \
    /downloads

[[ ! -f /config/.config/qBittorrent/qBittorrent.conf ]] && \
        cp /etc/defaults/qBittorrent.conf /config/.config/qBittorrent/

sed -i "s|Connection\\\PortRangeMin=.*|Connection\\\PortRangeMin=${PEER_PORT}|i" /config/.config/qBittorrent/qBittorrent.conf
sed -i "s|Downloads\\\SavePath=.*|Downloads\\\SavePath=/downloads|i" /config/.config/qBittorrent/qBittorrent.conf

chown -R ${UID}:${GID} /config

# Umask
UMASK=${UMASK:-022}
umask "$UMASK"

export HOME="/config"

exec s6-setuidgid ${UID}:${GID} qbittorrent-nox --webui-port=${WEBUI_PORT:-8989}
