#! /bin/sh
#
#  docker init

set -e

# setting up timezone
cp /usr/share/zoneinfo/${TZ} /etc/localtime
echo "${TZ}" > /etc/timezone

# user and priv
mkdir -p /config/qBittorrent/config/

[[ ! -f /config/qBittorrent/config/qBittorrent.conf ]] && \
        cp /etc/defaults/qBittorrent.conf /config/qBittorrent/config/

sed -i "s|Connection\\\PortRangeMin=.*|Connection\\\PortRangeMin=${PEER_PORT}|i" /config/qBittorrent/config/qBittorrent.conf

chown -R ${UID}:${GID} /config

# Umask
UMASK=${UMASK:-022}
umask "$UMASK"

exec s6-setuidgid ${UID}:${GID} qbittorrent-nox --webui-port=${WEBUI_PORT:-8989} --profile=/config
