name: CI

on:
  push:
      paths:
        - qbittorrent-ee/*
        - xware-rpi/*


jobs: 
    qbittorrent:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build ./qbittorrent-ee