name: CI

on:
  push:
      paths:
        - .github/workflows/ci.yml
        - qbittorrent-ee/**
        - shadowsocks-libev/**
        - chinadns_dnsmasq/**
        - subwatcher/**


jobs: 
    qbittorrent:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build ./qbittorrent-ee

    shadowsocks-libev:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build ./shadowsocks-libev

    dnsmasq-chinadns:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build ./chinadns_dnsmasq

    subwatcher:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build ./subwatcher