name: Dockerfile CI

on: [push]

jobs: 
    qbittorrent:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Vaild
              run: docker build -t qbittorrent-ee:test ./qbittorrent-ee-rpi