name: nginx-brotli

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  REPO_NAME: ly0007/nginx
  # BUILD_PLATFORM: linux/amd64,linux/arm/v7,linux/arm64
  BUILD_PLATFORM: linux/amd64

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'nginxinc/docker-nginx'

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PWD}}

      - name: Build Debian & Push
        run: docker buildx build
          --build-arg ENABLED_MODULES="brotli"
          --platform=$BUILD_PLATFORM
          --tag $REPO_NAME:latest
          --push
          ./modules
          
      - name: Build Alpine & Push
        run: docker buildx build
          --build-arg ENABLED_MODULES="brotli"
          --platform=$BUILD_PLATFORM
          --tag $REPO_NAME:alpine
          --push
          ./modules/Dockerfile.alpine
