name: RPiPlay

on:
  push:
      branches:
          - master
      paths:
          - rpiplay/**
          - .github/workflows/rpiplay.yml

env:
    REPO_NAME: ly0007/rpiplay

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Setup BuildX
              uses: docker/setup-buildx-action@v1
            - name: Login
              run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PWD}}
            - name: Build & Push
              run: docker buildx build 
               --platform=linux/arm/v7,linux/arm64
               --tag $REPO_NAME:latest 
               --push 
               ./rpiplay

