name: Shadowsocks-libev

on:
    push:
        branches:
            - master
        paths:
            - shadowsocks-libev/**
            - .github/workflows/shadowsocks-libev.yml

env:
    REPO_NAME: ly0007/shadowsocks-libev

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup BuildX
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                version: latest
            - name: Login
              run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PWD}}
            - name: Build & Push
              run: docker buildx build 
               --platform=linux/amd64,linux/arm/v7,linux/arm64 
               --tag $REPO_NAME:latest 
               --push 
               ./shadowsocks-libev 
            - name: Build SSR & Push
              run: docker buildx build 
               --platform=linux/amd64,linux/arm/v7,linux/arm64 
               --tag $REPO_NAME:latest-ssr 
               --push 
               ./shadowsocks-libev 
               -f ./shadowsocks-libev/Dockerfile.ssr